AppName = "HelpMeChooseIOS"
Schema = "HelpMeChooseIOS"
BundleId = "io.tuist.HelpMeChoose"

ApiKeyPath = "fastlane/29H93BJQ55.json"
KeyChainName = "291KeyChain"
KeyChainPassword = "dlrndurdmldlfemddmsdnfl"
CertificatePath = "Certification/FastalneKey.p12"
CertificatePath2 = "Certification/DevelopKey.p12"
CertificatePassword = "dlrndurdmldlfemddmsdnfl"
ProvisioningProfiles = "Fastalne"
InstallProvisioningProfile = "Certification/Develop.mobileprovision"
FastlaneProvisioningProfile = "Certification/Fastlane.mobileprovision"


#ENV['MATCH_GIT_BEARER_AUTHORIZATION'] = 'dlrndurdmldlfemddmsdnfl'



desc "build app and upload to testflight"
	lane :NewVersionUpload do
	fastlaneSetting
	
	increment_build_number(
            xcodeproj: AppName + ".xcodeproj",
            build_number: 1
       	)
	
	buildApp "Debug"

	testFlightUpload
   	
end


desc "build app and upload to testflight"
	lane :DevServerUpload do
	fastlaneSetting

    	latest_build_number=latest_testflight_build_number(
		api_key_path: ApiKeyPath
	)
	devBuild latest_build_number
   	upload_to_testflight(
		api_key_path: ApiKeyPath
	)
end



desc "build app and upload to testflight"
	lane :ProdServerUpload do
	fastlaneSetting

    	latest_build_number=latest_testflight_build_number(
		api_key_path: ApiKeyPath
	)

	prodBuild latest_build_number
   	
	upload_to_testflight(
		api_key_path: ApiKeyPath
	)
end



def createKeyChain
     	create_keychain(
		name: KeyChainName ,
		password: KeyChainPassword,
		timeout: 1800,
		default_keychain: true,
		unlock: true
	)
	


end


def importCertificate
	import_certificate(
  		certificate_path: CertificatePath,
  		certificate_password: CertificatePassword,
  		keychain_name: KeyChainName ,
  		keychain_password: KeyChainPassword
	)
	import_certificate(
  		certificate_path: CertificatePath2,
  		certificate_password: CertificatePassword,
  		keychain_name: KeyChainName ,
  		keychain_password: KeyChainPassword
	)  


end


def incrementBuildNumber
	increment_build_number(
            	xcodeproj: AppName + ".xcodeproj"
        	)
end





def fastlaneSetting
#	createKeyChain   
#	importCertificate
#	install_provisioning_profile(path: InstallProvisioningProfile)
#	install_provisioning_profile(path: FastlaneProvisioningProfile)

	sync_code_signing(
      		type: "appstore",
      		app_identifier: 'io.tuist.HelpMeChoose',
      		readonly: false
    	)  

end

def buildApp(configuration)



	build_app(
		workspace: AppName + ".xcworkspace", scheme: Schema , configuration: configuration ,
		export_options: {
     			provisioningProfiles: { 
        				Schema => ProvisioningProfiles
     			}
    		}
    	)
end


def testFlightUpload



	upload_to_testflight(
		api_key_path: ApiKeyPath ,
		
	)

end
 