name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: ${{ secrets.KNOWN_HOSTS }}
        user: root
        key: ${{ secrets.SSH_KEY}}

    - name: Fastlane Install
      run: brew install fastlane
             
    - name: Fastlane Match
      run: fastlane match appstore
    - name: Fsatlane NewVersionUpload
      run: fastlane NewVersionUpload
