name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: executing remote ssh commands using password
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}          
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Fastlane Install
      run: brew install fastlane
             
    - name: Fastlane Match
      run: fastlane match appstore
    - name: Fsatlane NewVersionUpload
      run: fastlane NewVersionUpload
