name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
        - actions/checkout@v2
        - uses: webfactory/ssh-agent@v0.5.4
          with:
            sh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#
#    - name: gitName
#      run: |
#        git config --global user.email gnejfejf3@naver.com 
#        git config --global user.name gnejfejf2
#    - name: Fastlane Match
#      run: |
#        fastlane match appstore
