name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
#    - name: executing remote ssh commands using password
#      uses: shimataro/ssh-key-action@v2
#      with:
#        key: ${{ secrets.SSH_KEY }} 
#        name: id_rsa
#        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
    - name: Generate project
      run: |
          tuist generate
    - name: Fastlane Match
      run: |
        fastlane certificates
    - name: Fastlane Upload
      run: |
        fastlane NewVersionUpload
      env:
        API_KEY_ID: '${{ secrets.API_KEY_ID }}'
