name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
    - name: Generate project
      run: |
          tuist generate
    - name: executing remote ssh commands using password
      uses: shimataro/ssh-key-action@v2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
    - name: Fastlane Setting
      run : fastlane match appstore
    - name: Fastlane Install
      run: brew install fastlane
    - name: Fsatlane NewVersionUpload
      run: fastlane NewVersionUpload
