name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }} 
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}


    - name: gitName
      run: |
        git config --global user.name gnejfejf2
    
    - name: gitid
      run: | 
        git remote set-url origin https://github.com/gnejfejf2/HelpMeChoose.git

    - name: Fastlane Match
      run: |
        fastlane match appstore
        env:
          MATCH_PASSWORD: ${{ secrets.SSH_KEY }}
