name: Swift

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v2
        - name: gitName
          env:
            ssh-private-key: ${{ secrets.SSH_KEY }}
          run: |
            echo $ssh-private-key

        
        
        - uses: webfactory/ssh-agent@v0.5.4
          env:
            ssh-private-key: ${{ secrets.SSH_KEY }}
          with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
#
#
#    - name: gitName
#      run: |
#        git config --global user.email gnejfejf3@naver.com 
#        git config --global user.name gnejfejf2
#    - name: Fastlane Match
#      run: |
#        fastlane match appstore
